#include <Process.au3>
_RunDOS("regsvr32 /u DvrOcx.ocx")
;WinWait("RegSvr32","È·¶¨")
Send("{enter}")
FileDelete("c:\Windows\system32\AmrDll.dll")
FileDelete("c:\Windows\system32\AudioDecoder.dll")
FileDelete("c:\Windows\system32\avcodec.dll")
FileDelete("c:\Windows\system32\avformat.dll")
FileDelete("c:\Windows\system32\avutil.dll")
FileDelete("c:\Windows\system32\chipdecoder.dll")
FileDelete("c:\Windows\system32\coreavc.ax")
FileDelete("c:\Windows\system32\CovH264ToAvi.dll")
FileDelete("c:\Windows\system32\DivXDecH264.ax")

FileDelete("c:\Windows\system32\DivXMedia.ax")
FileDelete("c:\Windows\system32\DvrOcx.ocx")
FileDelete("c:\Windows\system32\ffdshow.ax")
FileDelete("c:\Windows\system32\gdiplus.dll")
FileDelete("c:\Windows\system32\hi_h264dec.dll")
FileDelete("c:\Windows\system32\hi_h264dec_w.dll")
FileDelete("c:\Windows\system32\l3codecp.acm")
FileDelete("c:\Windows\system32\lib_VoiceEngine_dll.dll")
FileDelete("c:\Windows\system32\libavcodec.dll")
FileDelete("c:\Windows\system32\libmplayer.dll")
FileDelete("c:\Windows\system32\Logo_Language.ini")
FileDelete("c:\Windows\system32\mfc42.dll")
FileDelete("c:\Windows\system32\MSVCP60.DLl")
FileDelete("c:\Windows\system32\msvcrt.dll")
FileDelete("c:\Windows\system32\nvrfs.dll")
FileDelete("c:\Windows\system32\OggSplitter.ax")

FileDelete("c:\Windows\system32\pthreadGC2.dll")
FileDelete("c:\Windows\system32\RealMediaSplitter.ax")
FileDelete("c:\Windows\system32\RM_DvrAVDecoder.dll")
FileDelete("c:\Windows\system32\RM_DVRNET_DLL.dll")
FileDelete("c:\Windows\system32\VSFilter.dll")
FileDelete("c:\Windows\system32\winpubf.dll")
FileDelete("c:\Windows\system32\xvidcore.dll")
