#include <Process.au3>
_RunDOS("regsvr32 /u HiDvrOcx.ocx")
;WinWait("RegSvr32","确定")
Sleep(2000)
If WinExists("RegSvr32","确定") Then
	Send("{enter}")
    MsgBox(1, "文件已删除", "文件已经删除了")
EndIf
FileDelete("c:\Windows\system32\hidvr*")
FileDelete("c:\Windows\system32\AudioPlayer.dll")
FileDelete("c:\Windows\system32\HiDvrMedia.dll")
FileDelete("c:\Windows\system32\HiDvrNet.dll")
FileDelete("c:\Windows\system32HiDvrOcx.ocx")
FileDelete("c:\Windows\system32\HiDvrOcxCHS.dll")
FileDelete("c:\Windows\system32\HiDvrOcxCHT.dll")
FileDelete("c:\Windows\system32\AudioPlayer.dll")
FileDelete("c:\Windows\system32\HiDvrMedia.dll")
#cs
FileDelete("c:\Windows\system32\RM_DvrAVDecoder.dll")
FileDelete("c:\Windows\system32\RM_DVRNET_DLL.dll")
FileDelete("c:\Windows\system32\Logo_Language.ini")
FileDelete("c:\Windows\system32\AmrDll.dll")
FileDelete("c:\Windows\system32\AudioDecoder.dll")
FileDelete("c:\Windows\system32\chipdecoder.dll")
FileDelete("c:\Windows\system32\CovH264ToAvi.dll")
FileDelete("c:\Windows\system32\DvrOcx.inf")
FileDelete("c:\Windows\system32\hi_h264dec.dll")
FileDelete("c:\Windows\system32\hi_h264dec_w.dll")
FileDelete("c:\Windows\system32\lib_VoiceEngine_dll.dll")
FileDelete("c:\Windows\system32\ Logo_Language.ini")
FileDelete("c:\Windows\system32\nvrfs.dll")
FileDelete("c:\Windows\system32\winpubf.dll")
FileDelete("c:\Windows\system32\dvr*")
#ce