#include <Process.au3>
_RunDOS(@SystemDir & "regsvr32 /u HiDvrOcx.ocx")
;WinWait("RegSvr32","确定")
Sleep(2000)
If WinExists("RegSvr32","确定") Then
	Send("{enter}")
    MsgBox(1, "文件已删除", "文件已经删除了")
EndIf

FileDelete(@SystemDir & "\RSVideo.ocx")
FileDelete(@SystemDir & "\AVI.dll")
FileDelete(@SystemDir & "\hi_h264dec_w.dll")
FileDelete(@SystemDir & "hisi_voice_engine.dll")
FileDelete(@SystemDir & "\lib_VoiceEngine_dll.dll")
FileDelete(@SystemDir & "\RSNet.dll")
FileDelete(@SystemDir & "\RSPlay.dll")
FileDelete(@SystemDir & "\RSSkinLorex.dll")
FileDelete(@SystemDir & "\RSSkinFlir.dll")
FileDelete(@SystemDir & "\RSSkinNormal.dll")
FileDelete(@SystemDir & "\RSSkinKguard.dll")
FileDelete(@SystemDir & "\RSSkinHoneywell.dll")
FileDelete(@SystemDir & "\RSSkinHiviewer.dll")
FileDelete(@SystemDir & "\RSSkinGreatek.dll")
FileDelete(@SystemDir & "\CHS.xml")
FileDelete(@SystemDir & "\ENU.xml")
FileDelete(@SystemDir & "\HEB.xml")
FileDelete(@SystemDir & "\ITA.xml")
FileDelete(@SystemDir & "\PTG.xml")
FileDelete(@SystemDir & "\RUS.xml")
FileDelete(@SystemDir & "\TUR.xml")
#cs
FileDelete("\RM_DvrAVDecoder.dll")
FileDelete("\RM_DVRNET_DLL.dll")
FileDelete("\Logo_Language.ini")
FileDelete("\AmrDll.dll")
FileDelete("\AudioDecoder.dll")
FileDelete("\chipdecoder.dll")
FileDelete("\CovH264ToAvi.dll")
FileDelete("\DvrOcx.inf")
FileDelete("\hi_h264dec.dll")
FileDelete("\hi_h264dec_w.dll")
FileDelete("\lib_VoiceEngine_dll.dll")
FileDelete("\ Logo_Language.ini")
FileDelete("\nvrfs.dll")
FileDelete("\winpubf.dll")
FileDelete("\dvr*")
#ce


