WinActivate ("Serial-COM1 - SecureCRT","")
ControlClick("Serial-COM1 - SecureCRT","",11796)
Send("config net")
Send("{enter}")
Send("1")
Send("{enter}")
Send("10.0.254.2")
Send("{enter 4}")
Send("10.0.254.168")
Send("{enter 4}")
Send("download net romfs")
Send("{enter}")
Sleep(10000)
Send("flash romfs")
Send("{enter}")