ShellExecute("QQPCMgr.exe","","N:\toors\QQPCMgr\4.7.1252.201")
WinWait("QQ电脑管家4.7")
MouseClick("left",1032, 259,1)
WinWait("关联QQ帐号")
WinActivate("关联QQ帐号")
ControlClick("关联QQ帐号","","ATL:30A4D1F01")
Send("帐号")
ControlClick("关联QQ帐号","","Edit1")
Send("密码")
Send("{Tab}")
Send("{Tab}")
Send("{space}")
Send("{tab}")
Send("{enter}")